# Default values for hello-world.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
frontend:
  image:
    repository: ryuunosukeds3/hello-world-frontend
    # This sets the pull policy for images.
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  service:
    # This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
    type: ClusterIP
    # This sets the service port (default: 4200 for Angular dev server)
    port: 4200
  ingress:
    # Set to true to enable ingress for the frontend
    enabled: false
    # Set your ingress class name (e.g., nginx, traefik)
    className: ""
    annotations:
      {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: frontend.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: frontend-tls
    #    hosts:
    #      - frontend.local

backend:
  image:
    repository: ryuunosukeds3/hello-world-backend
    # This sets the pull policy for images.
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  defaultTheme: light
  service:
    # This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
    type: ClusterIP
    # This sets the service port (default: 4200 for Angular dev server)
    port: 3000

  ingress:
    enabled: false
    className: ""
    annotations:
      {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: backend.local
        paths:
          - path: /
            pathType: ImplementationSpecific
          - path: /api/
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: backend-tls
    #    hosts:
    #      - backend.local
