name: Publish Helm Chart

on:
  push:
    branches:
      - main

jobs:
  package-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.3

      - name: Package Helm chart
        run: |
          helm package ./hello-world  # adjust path if your chart is in a different folder
          mkdir -p repo

      - name: Download and fetch gh-pages branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git clone --branch gh-pages https://github.com/${{ github.repository }} repo || git clone https://github.com/${{ github.repository }} repo
          cd repo

      - name: Copy packaged chart to repo
        run: |
          cp ../*.tgz repo/
          cd repo

      - name: Update Helm repo index
        run: |
          cd repo
          helm repo index . --url https://ryuunosukeds3.github.io/hello-world-charts

      - name: Commit and push changes to gh-pages
        run: |
          cd repo
          git add .
          git commit -m "Publish Helm chart ${{ github.sha }}" || echo "No changes to commit"
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
